// Register
export const REGISTER_CLIENT_START = 'REGISTER_CLIENT_START';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAIL = 'REGISTER_CLIENT_FAIL';

export const REGISTER_AGENT_START = 'REGISTER_AGENT_START';
export const REGISTER_AGENT_SUCCESS = 'REGISTER_AGENT_SUCCESS';
export const REGISTER_AGENT_FAIL = 'REGISTER_AGENT_FAIL';

export const RECOVER_PASSWORD_START = 'RECOVER_PASSWORD_START';
export const RECOVER_PASSWORD_FAIL = 'RECOVER_PASSWORD_FAIL';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';

// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Login with Facebook
export const CLIENT_FACEBOOK_LOGIN_START = 'CLIENT_FACEBOOK_LOGIN_START';
export const CLIENT_FACEBOOK_LOGIN_SUCCESS = 'CLIENT_FACEBOOK_LOGIN_SUCCESS';
export const CLIENT_FACEBOOK_LOGIN_FAIL = 'CLIENT_FACEBOOK_LOGIN_FAIL';

// Properties
export const FETCH_PROPERTIES_START = 'FETCH_PROPERTIES_START';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAIL = 'FETCH_PROPERTIES_FAIL';

// SHOW Property
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';

// Create Property
export const CREATE_PROPERTY_START = 'CREATE_PROPERTY_START';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAIL = 'CREATE_PROPERTY_FAIL';

// Update Property
export const UPDATE_PROPERTY_START = 'UPDATE_PROPERTY_START';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_FAIL = 'UPDATE_PROPERTY_FAIL';

// Delete Property
export const DELETE_PROPERTY_START = 'DELETE_PROPERTY_START';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAIL = 'DELETE_PROPERTY_FAIL';

// Delete Card
export const DELETE_CARD_START = 'DELETE_CARD_START';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAIL = 'DELETE_CARD_FAIL';

// Services
export const FETCH_SERVICES_START = 'FETCH_SERVICES_START';
export const FETCH_SERVICES_FAIL = 'FETCH_SERVICES_FAIL';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICE_START = 'FETCH_SERVICE_START';
export const FETCH_SERVICE_FAIL = 'FETCH_SERVICE_FAIL';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';

export const HOLIDAYS_START = 'HOLIDAYS_START';
export const HOLIDAYS_FAIL = 'HOLIDAYS_FAIL';
export const HOLIDAYS_SUCCESS = 'HOLIDAYS_SUCCESS';

export const INVOICES_START = 'INVOICES_START';
export const INVOICES_FAIL = 'INVOICES_FAIL';
export const INVOICES_SUCCESS = 'INVOICES_SUCCESS';

export const CREATED_INVOICE_START = 'CREATED_INVOICE_START';
export const CREATED_INVOICE_FAIL = 'CREATED_INVOICE_FAIL';
export const CREATED_INVOICE_SUCCESS = 'CREATED_INVOICE_SUCCESS';

export const DELETE_INVOICE_START = 'DELETE_INVOICE_START';
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';

// Cities
export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';

// Neightborhoods
export const FETCH_NEIGHTBORHOODS_START = 'FETCH_NEIGHTBORHOODS_START';
export const FETCH_NEIGHTBORHOODS_FAIL = 'FETCH_NEIGHTBORHOODS_FAIL';
export const FETCH_NEIGHTBORHOODS_SUCCESS = 'FETCH_NEIGHTBORHOODS_SUCCESS';

// Jobs
export const CREATE_JOB_START = 'CREATE_JOB_START';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';

export const FETCH_NEXTJOBS_START = 'FETCH_NEXTJOBS_START';
export const FETCH_NEXTJOBS_SUCCESS = 'FETCH_NEXTJOBS_SUCCESS';
export const FETCH_NEXTJOBS_FAIL = 'FETCH_NEXTJOBS_FAIL';

export const FETCH_NEXTJOBS_CURRENT_START = 'FETCH_NEXTJOBS_CURRENT_START';
export const FETCH_NEXTJOBS_CURRENT_SUCCESS = 'FETCH_NEXTJOBS_CURRENT_SUCCESS';
export const FETCH_NEXTJOBS_CURRENT_FAIL = 'FETCH_NEXTJOBS_CURRENT_FAIL';

export const FETCH_HISTORYJOBS_START = 'FETCH_HISTORYJOBS_START';
export const FETCH_HISTORYJOBS_SUCCESS = 'FETCH_HISTORYJOBS_SUCCESS';
export const FETCH_HISTORYJOBS_FAIL = 'FETCH_HISTORYJOBS_FAIL';

export const FETCH_LIST_JOBS_COMPLETED_START = 'FETCH_LIST_JOBS_COMPLETED_START';
export const FETCH_LIST_JOBS_COMPLETED_SUCCESS = 'FETCH_LIST_JOBS_COMPLETED_SUCCESS';
export const FETCH_LIST_JOBS_COMPLETED_FAIL = 'FETCH_LIST_JOBS_COMPLETED_FAIL';

export const FETCH_JOB_START = 'FETCH_JOB_START';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

export const ACCEPTED_JOB_START = 'ACCEPTED_JOB_START';
export const ACCEPTED_JOB_SUCCESS = 'ACCEPTED_JOB_SUCCESS';
export const ACCEPTED_JOB_FAIL = 'ACCEPTED_JOB_FAIL';

export const CANCELLED_JOB_START = 'CANCELLED_JOB_START';
export const CANCELLED_JOB_SUCCESS = 'CANCELLED_JOB_SUCCESS';
export const CANCELLED_JOB_FAIL = 'CANCELLED_JOB_FAIL';

export const FETCH_AGENT_JOBS_START = 'FETCH_AGENT_JOBS_START';
export const FETCH_AGENT_JOBS_SUCCESS = 'FETCH_AGENT_JOBS_SUCCESS';
export const FETCH_AGENT_JOBS_FAIL = 'FETCH_AGENT_JOBS_FAIL';

// Current user
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';

export const UPDATED_CURRENT_USER_START = 'UPDATED_CURRENT_USER_START';
export const UPDATED_CURRENT_USER_SUCCESS = 'UPDATED_CURRENT_USER_SUCCESS';
export const UPDATED_CURRENT_USER_FAIL = 'UPDATED_CURRENT_USER_FAIL';

export const UPDATED_CURRENT_USER_AVATAR_START = 'UPDATED_CURRENT_USER_AVATAR_START';
export const UPDATED_CURRENT_USER_AVATAR_SUCCESS = 'UPDATED_CURRENT_USER_AVATAR_SUCCESS';
export const UPDATED_CURRENT_USER_AVATAR_FAIL = 'UPDATED_CURRENT_USER_AVATAR_FAIL';

export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const FETCH_CURRENT_AGENT_START = 'FETCH_CURRENT_AGENT_START';
export const FETCH_CURRENT_AGENT_FAIL = 'FETCH_CURRENT_AGENT_FAIL';
export const FETCH_CURRENT_AGENT_SUCCESS = 'FETCH_CURRENT_AGENT_SUCCESS';

export const UPDATED_CURRENT_AGENT_START = 'UPDATED_CURRENT_AGENT_START';
export const UPDATED_CURRENT_AGENT_SUCCESS = 'UPDATED_CURRENT_AGENT_SUCCESS';
export const UPDATED_CURRENT_AGENT_FAIL = 'UPDATED_CURRENT_AGENT_FAIL';

export const UPDATED_CURRENT_AGENT_AVATAR_START = 'UPDATED_CURRENT_AGENT_AVATAR_START';
export const UPDATED_CURRENT_AGENT_AVATAR_SUCCESS = 'UPDATED_CURRENT_AGENT_AVATAR_SUCCESS';
export const UPDATED_CURRENT_AGENT_AVATAR_FAIL = 'UPDATED_CURRENT_AGENT_AVATAR_FAIL';

export const CHANGE_PASSWORD_AGENT_START = 'CHANGE_PASSWORD_AGENT_START';
export const CHANGE_PASSWORD_AGENT_SUCCESS = 'CHANGE_PASSWORD_AGENT_SUCCESS';
export const CHANGE_PASSWORD_AGENT_FAIL = 'CHANGE_PASSWORD_AGENT_FAIL';

export const APPLY_PROPOSAL_START = 'APPLY_PROPOSAL_START';
export const APPLY_PROPOSAL_SUCCESS = 'APPLY_PROPOSAL_SUCCESS';
export const APPLY_PROPOSAL_FAIL = 'APPLY_PROPOSAL_FAIL';

export const FETCH_JOB_AGENT_CURRENT_START = 'FETCH_JOB_AGENT_CURRENT_START';
export const FETCH_JOB_AGENT_CURRENT_SUCCESS = 'FETCH_JOB_AGENT_CURRENT_SUCCESS';
export const FETCH_JOB_AGENT_CURRENT_FAIL = 'FETCH_JOB_AGENT_CURRENT_FAIL';

export const FETCH_JOB_AGENT_COMPLETED_START = 'FETCH_JOB_AGENT_COMPLETED_START';
export const FETCH_JOB_AGENT_COMPLETED_SUCCESS = 'FETCH_JOB_AGENT_COMPLETED_SUCCESS';
export const FETCH_JOB_AGENT_COMPLETED_FAIL = 'FETCH_JOB_AGENT_COMPLETED_FAIL';

export const FETCH_JOB_AGENT_POSTULATED_START = 'FETCH_JOB_AGENT_POSTULATED_START';
export const FETCH_JOB_AGENT_POSTULATED_SUCCESS = 'FETCH_JOB_AGENT_POSTULATED_SUCCESS';
export const FETCH_JOB_AGENT_POSTULATED_FAIL = 'FETCH_JOB_AGENT_POSTULATED_FAIL';

export const SHOW_REVIEWS_START = 'SHOW_REVIEWS_START';
export const SHOW_REVIEWS_SUCCESS = 'SHOW_REVIEWS_SUCCESS';
export const SHOW_REVIEWS_FAIL = 'SHOW_REVIEWS_FAIL';

export const PROPOSAL_POSTULATE_START = 'PROPOSAL_POSTULATE_START';
export const PROPOSAL_POSTULATE_SUCCESS = 'PROPOSAL_POSTULATE_SUCCESS';
export const PROPOSAL_POSTULATE_FAIL = 'PROPOSAL_POSTULATE_FAIL';

export const JOB_DETAILS_START = 'JOB_DETAILS_START';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL';

export const QUALIFY_START = 'QUALIFY_START';
export const QUALIFY_SUCCESS = 'QUALIFY_SUCCESS';
export const QUALIFY_FAIL = 'QUALIFY_FAIL';

export const QUALIFY_CUSTOMER_START = 'QUALIFY_CUSTOMER_START';
export const QUALIFY_CUSTOMER_SUCCESS = 'QUALIFY_CUSTOMER_SUCCESS';
export const QUALIFY_CUSTOMER_FAIL = 'QUALIFY_CUSTOMER_FAIL';

export const DISABLE_BUTTON_START = 'DISABLE_BUTTON_START';
export const DISABLE_BUTTON_SUCCESS = 'DISABLE_BUTTON_SUCCESS';
export const DISABLE_BUTTON_FAIL = 'DISABLE_BUTTON_FAIL';

export const DISABLE_BUTTON_CUSTOMER_START = 'DISABLE_BUTTON_CUSTOMER_START';
export const DISABLE_BUTTON_CUSTOMER_SUCCESS = 'DISABLE_BUTTON_CUSTOMER_SUCCESS';
export const DISABLE_BUTTON_CUSTOMER_FAIL = 'DISABLE_BUTTON_CUSTOMER_FAIL';

export const JOB_CALENDAR_START = 'JOB_CALENDAR_START';
export const JOB_CALENDAR_FAIL = 'JOB_CALENDAR_FAIL';
export const JOB_CALENDAR_SUCCESS = 'JOB_CALENDAR_SUCCESS';

export const CAN_APPLY_START = 'CAN_APPLY_START';
export const CAN_APPLY_FAIL = 'CAN_APPLY_FAIL';
export const CAN_APPLY_SUCCESS = 'CAN_APPLY_SUCCESS';

export const FORM_CONTACT_START = 'FORM_CONTACT_START';
export const FORM_CONTACT_FAIL = 'FORM_CONTACT_FAIL';
export const FORM_CONTACT_SUCCESS = 'FORM_CONTACT_SUCCESS';

export const REVIEWS_START = 'REVIEWS_START';
export const REVIEWS_FAIL = 'REVIEWS_FAIL';
export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS';

export const REVIEWS_AGENT_START = 'REVIEWS_AGENT_START';
export const REVIEWS_AGENT_FAIL = 'REVIEWS_AGENT_FAIL';
export const REVIEWS_AGENT_SUCCESS = 'REVIEWS_AGENT_SUCCESS';

export const FETCH_JOB_AGENT_REPORT_START = 'FETCH_JOB_AGENT_REPORT_START';
export const FETCH_JOB_AGENT_REPORT_SUCCESS = 'FETCH_JOB_AGENT_REPORT_SUCCESS';
export const FETCH_JOB_AGENT_REPORT_FAIL = 'FETCH_JOB_AGENT_REPORT_FAIL';

export const NOTIFICATIONS_AGENT_START = 'NOTIFICATIONS_AGENT_START';
export const NOTIFICATIONS_AGENT_SUCCESS = 'NOTIFICATIONS_AGENT_SUCCESS';
export const NOTIFICATIONS_AGENT_FAIL = 'NOTIFICATIONS_AGENT_FAIL';

export const NOTIFICATIONS_AGENT_READ_START = 'NOTIFICATIONS_AGENT_READ_START';
export const NOTIFICATIONS_AGENT_READ_SUCCESS = 'NOTIFICATIONS_AGENT_READ_SUCCESS';
export const NOTIFICATIONS_AGENT_READ_FAIL = 'NOTIFICATIONS_AGENT_READ_FAIL';

export const NOTIFICATIONS_CUSTOMER_START = 'NOTIFICATIONS_CUSTOMER_START';
export const NOTIFICATIONS_CUSTOMER_SUCCESS = 'NOTIFICATIONS_CUSTOMER_SUCCESS';
export const NOTIFICATIONS_CUSTOMER_FAIL = 'NOTIFICATIONS_CUSTOMER_FAIL';

export const NOTIFICATIONS_CUSTOMER_READ_START = 'NOTIFICATIONS_CUSTOMER_READ_START';
export const NOTIFICATIONS_CUSTOMER_READ_SUCCESS = 'NOTIFICATIONS_CUSTOMER_READ_SUCCESS';
export const NOTIFICATIONS_CUSTOMER_READ_FAIL = 'NOTIFICATIONS_CUSTOMER_READ_FAIL';

export const PAYMENT_ADD_CARD_START = 'PAYMENT_ADD_CARD_START';
export const PAYMENT_ADD_CARD_SUCCESS = 'PAYMENT_ADD_CARD_SUCCESS';
export const PAYMENT_ADD_CARD_FAIL = 'PAYMENT_ADD_CARD_FAIL';

export const LIST_CARD_START = 'LIST_CARD_START';
export const LIST_CARD_SUCCESS = 'LIST_CARD_SUCCESS';
export const LIST_CARD_FAIL = 'LIST_CARD_FAIL';

export const CONFIRMATION_PAYMENT_START = 'CONFIRMATION_PAYMENT_START';
export const CONFIRMATION_PAYMENT_SUCCESS = 'CONFIRMATION_PAYMENT_SUCCESS';
export const CONFIRMATION_PAYMENT_FAIL = 'CONFIRMATION_PAYMENT_FAIL';

export const VALIDATE_CODE_START = 'VALIDATE_CODE_START';
export const VALIDATE_CODE_SUCCESS = 'VALIDATE_CODE_SUCCESS';
export const VALIDATE_CODE_FAIL = 'VALIDATE_CODE_FAIL';